# Generated by Django 5.0.6 on 2026-03-23 14:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('validation_deadline_days', models.IntegerField(default=5)),
                ('dispute_resolution_hours', models.IntegerField(default=48)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('influencer', 'Influencer'), ('brand', 'Brand'), ('admin', 'Admin')], max_length=20)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('subscription_plan', models.CharField(blank=True, choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=20, null=True)),
                ('subscription_active', models.BooleanField(default=False)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('gifting', 'Gifting'), ('paid', 'Paid')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('products', models.JSONField(blank=True, default=list)),
                ('shipping_info', models.TextField(blank=True)),
                ('deliverables_requested', models.JSONField(blank=True, default=list)),
                ('brief_text', models.TextField(blank=True)),
                ('brief_files', models.FileField(blank=True, null=True, upload_to='briefs/')),
                ('target_networks', models.JSONField(blank=True, default=list)),
                ('content_format', models.CharField(blank=True, max_length=100)),
                ('price_per_influencer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('target_filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.brandprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('counter_offer', 'Counter Offer'), ('contract_signed', 'Contract Signed'), ('in_progress', 'In Progress'), ('content_submitted', 'Content Submitted'), ('validated', 'Validated'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=30)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counter_message', models.TextField(blank=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('contract_signed_brand', models.BooleanField(default=False)),
                ('contract_signed_influencer', models.BooleanField(default=False)),
                ('contract_signed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('escrow_funded', models.BooleanField(default=False)),
                ('escrow_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('link', 'Link'), ('upload', 'Upload')], max_length=10)),
                ('publication_url', models.URLField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('publication_date', models.DateTimeField()),
                ('initial_stats', models.JSONField(default=dict)),
                ('final_stats', models.JSONField(blank=True, null=True)),
                ('brand_validated', models.BooleanField(blank=True, null=True)),
                ('brand_validation_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('brief_not_followed', 'Brief Not Followed'), ('wrong_platform', 'Wrong Platform'), ('missing_mention', 'Missing Mention'), ('insufficient_quality', 'Insufficient Quality'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=30, null=True)),
                ('rejection_comment', models.TextField(blank=True)),
                ('admin_validated', models.BooleanField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.campaignproposal')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('content_themes', models.JSONField(default=list)),
                ('content_types_offered', models.JSONField(default=list)),
                ('pricing', models.JSONField(default=dict)),
                ('payment_method', models.CharField(blank=True, choices=[('iban', 'IBAN'), ('paypal', 'PayPal')], max_length=20)),
                ('payment_details', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='api.influencerprofile'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.campaignproposal')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_proposal', 'New Proposal'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_declined', 'Proposal Declined'), ('counter_offer', 'Counter Offer'), ('contract_ready', 'Contract Ready'), ('escrow_funded', 'Escrow Funded'), ('content_submitted', 'Content Submitted'), ('content_validated', 'Content Validated'), ('content_rejected', 'Content Rejected'), ('payment_released', 'Payment Released'), ('new_message', 'New Message'), ('new_review', 'New Review')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campaignproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.campaignproposal')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=20)),
                ('profile_url', models.URLField()),
                ('followers_count', models.IntegerField(default=0)),
                ('avg_views', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='api.influencerprofile')),
            ],
        ),
    ]
