# Generated by Django 5.1.14 on 2026-04-20 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='siret',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='casting_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_rights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_casting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='brand_signature_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='brand_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='contract_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='escrow_funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='influencer_signature_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='influencer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignproposal',
            name='validation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='correction_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='correction_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='media_kit_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='media_kit_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media_kits/'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='profile_completion_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='stripe_onboarding_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='criteria_ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='oauth_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='oauth_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='oauth_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='verified_via_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_proposal', 'New Proposal'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_declined', 'Proposal Declined'), ('counter_offer', 'Counter Offer'), ('contract_ready', 'Contract Ready'), ('contract_signed', 'Contract Signed'), ('escrow_funded', 'Escrow Funded'), ('content_submitted', 'Content Submitted'), ('content_validated', 'Content Validated'), ('content_rejected', 'Content Rejected'), ('payment_released', 'Payment Released'), ('new_message', 'New Message'), ('new_review', 'New Review'), ('brand_validated', 'Brand Validated'), ('brand_rejected', 'Brand Rejected'), ('subscription_changed', 'Subscription Changed'), ('casting_application', 'Casting Application')], max_length=30),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('pinterest', 'Pinterest'), ('twitch', 'Twitch'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat')], max_length=20),
        ),
        migrations.CreateModel(
            name='AmbassadorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kpis', models.JSONField(blank=True, default=dict)),
                ('bonus_rules', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=20)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_programs', to='api.brandprofile')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_programs', to='api.influencerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('brand_validated', 'Brand Validated'), ('brand_rejected', 'Brand Rejected'), ('escrow_funded', 'Escrow Funded'), ('escrow_released', 'Escrow Released'), ('escrow_refunded', 'Escrow Refunded'), ('contract_signed', 'Contract Signed'), ('content_validated', 'Content Validated'), ('content_rejected', 'Content Rejected'), ('admin_arbitrated', 'Admin Arbitrated'), ('subscription_created', 'Subscription Created'), ('subscription_changed', 'Subscription Changed'), ('subscription_cancelled', 'Subscription Cancelled'), ('user_suspended', 'User Suspended'), ('review_moderated', 'Review Moderated')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('body_html', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='api.brandprofile')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='api.contracttemplate'),
        ),
        migrations.CreateModel(
            name='CastingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField()),
                ('examples', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_applications', to='api.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_applications', to='api.influencerprofile')),
            ],
            options={
                'unique_together': {('campaign', 'influencer')},
            },
        ),
    ]
