# Generated by Django 5.1.14 on 2026-04-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brandprofile_siret_brandprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaKitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_kit_gallery/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_kit_images', to='api.influencerprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
