# Generated by Django 5.1.14 on 2026-04-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaign_max_influencers'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_formats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
