# Generated by Django 5.1.14 on 2026-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_campaign_content_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='contract_templates/'),
        ),
    ]
