# Generated by Django 5.1.14 on 2026-05-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproposal',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='api.contracttemplate'),
        ),
    ]
