# Generated by Django 5.1.14 on 2026-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_influencerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='content_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='media_kit_is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
