# Generated by Django 5.1.14 on 2026-05-10 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_influencerprofile_content_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='agency_default_commission_percent',
            field=models.DecimalField(decimal_places=2, default=20, help_text="Default commission percent applied on managed influencers' earnings.", max_digits=5),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AgencyDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('invitation_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_as_agency', to='api.brandprofile')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_delegations', to='api.influencerprofile')),
            ],
            options={
                'unique_together': {('agency', 'influencer')},
            },
        ),
        migrations.CreateModel(
            name='BrandMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked')], default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.brandprofile')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('brand', 'user'), name='uniq_brand_user_membership'), models.UniqueConstraint(condition=models.Q(('invited_email', ''), _negated=True), fields=('brand', 'invited_email'), name='uniq_brand_email_membership')],
            },
        ),
    ]
