# Generated by Django 5.1.14 on 2026-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_support_ticket_reply_images_translation_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local credentials'), ('google', 'Google SSO'), ('office365', 'Office 365 SSO'), ('saml', 'SAML SSO'), ('other_sso', 'Other SSO')], default='local', max_length=20),
        ),
    ]
