# Generated by Django 5.1.14 on 2026-05-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_auth_provider_for_sso_otp_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
