# Generated by Django 5.1.14 on 2026-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_support_followup_and_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='source_language',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
