# Generated by Django 5.1.14 on 2026-05-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_event_and_eventinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvitation',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to='api.influencerprofile'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_checkins', to='api.user'),
        ),
        migrations.AddConstraint(
            model_name='eventinvitation',
            constraint=models.UniqueConstraint(condition=~models.Q(invited_email=''), fields=('event', 'invited_email'), name='uniq_event_invitation_per_email'),
        ),
    ]
