# Generated by Django 5.1.15 on 2026-05-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_socialstatssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='external_user_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='external_username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='is_verified_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='token_status',
            field=models.CharField(choices=[('none', 'None'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='total_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignVideoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('pinterest', 'Pinterest'), ('twitch', 'Twitch'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat')], max_length=20)),
                ('external_video_id', models.CharField(max_length=128)),
                ('video_url', models.URLField(max_length=600)),
                ('caption', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=600)),
                ('tracking_started_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_videos', to='api.campaignproposal')),
                ('social_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_campaign_videos', to='api.socialnetwork')),
            ],
            options={
                'ordering': ['-tracking_started_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignVideoDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('share_count', models.BigIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='api.campaignvideotracking')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialFraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('follower_spike', 'Follower spike'), ('low_engagement', 'Low engagement'), ('zombie_account', 'Zombie account')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='api.socialnetwork')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_video_id', models.CharField(max_length=128)),
                ('caption', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=600)),
                ('video_url', models.URLField(blank=True, max_length=600)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('share_count', models.BigIntegerField(default=0)),
                ('duration_sec', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.socialnetwork')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignvideotracking',
            constraint=models.UniqueConstraint(fields=('proposal', 'platform', 'external_video_id'), name='uniq_tracked_video_per_proposal'),
        ),
        migrations.AddConstraint(
            model_name='campaignvideodailystats',
            constraint=models.UniqueConstraint(fields=('tracking', 'snapshot_date'), name='uniq_tracked_video_stats_per_day'),
        ),
        migrations.AddIndex(
            model_name='socialfraudflag',
            index=models.Index(fields=['social_network', 'flag_type', 'resolved_at'], name='api_socialf_social__ba4b4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialvideo',
            constraint=models.UniqueConstraint(fields=('social_network', 'external_video_id'), name='uniq_social_video_per_account'),
        ),
    ]
