# Generated by Django 5.1.15 on 2026-05-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_sso_apikey_webhook'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiauditlog',
            new_name='api_apiaudi_brand_i_5483bc_idx',
            old_name='api_apiaudi_brand_i_idx',
        ),
        migrations.RenameIndex(
            model_name='apiauditlog',
            new_name='api_apiaudi_api_key_30b20a_idx',
            old_name='api_apiaudi_apikey_i_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='api_webhook_endpoin_485621_idx',
            old_name='api_webhook_endpoin_i_idx',
        ),
        migrations.AlterField(
            model_name='apiauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branddomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brandssoconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
