# Generated by ChatGPT on 2026-06-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_api_apiaudi_brand_i_idx_api_apiaudi_brand_i_5483bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_brand_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='api.brandprofile'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='referral_code_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='referral_commission_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount points applied to the platform commission for this influencer.', max_digits=5),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='api.influencerprofile'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_commission_discount_percent',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
        migrations.CreateModel(
            name='InfluencerReferralInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referral_code_snapshot', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='sent', max_length=20)),
                ('invitation_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_referral_invites', to='api.influencerprofile')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referral_invites', to='api.influencerprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='influencerreferralinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'sent')), fields=('inviter', 'invited_email'), name='uniq_open_referral_invite_per_email'),
        ),
    ]
