# Generated by Django 5.1.15 on 2026-06-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_backfill_brand_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandssoconfig',
            name='apply_to_organization',
            field=models.BooleanField(default=True, help_text='Grant access at the organization level (all environments) instead of this single environment.'),
        ),
        migrations.AddField(
            model_name='brandssoconfig',
            name='provisioning_mode',
            field=models.CharField(choices=[('domain', 'Everyone on a verified domain'), ('groups', 'Members of synchronized Entra groups only')], default='domain', max_length=12),
        ),
        migrations.CreateModel(
            name='SSOGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_object_id', models.CharField(max_length=64)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('scope', models.CharField(choices=[('global', 'All environments (global)'), ('environments', 'Selected environments')], default='global', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environments', models.ManyToManyField(blank=True, related_name='sso_group_mappings', to='api.brandprofile')),
                ('sso_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='api.brandssoconfig')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sso_config', 'group_object_id'), name='uniq_sso_group_mapping')],
            },
        ),
    ]
