# Generated by Django 5.1.15 on 2026-06-11 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_brandssoconfig_apply_to_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='subscription_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price (EUR) negotiated for this brand; empty = global plan price.', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price_eur_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
