# Generated by Django 5.2.17 on 2026-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_campaign_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_ugc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='is_ugc_creator',
            field=models.BooleanField(default=False),
        ),
    ]
