# Generated by Django 5.2.17 on 2026-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_ugc_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='annual_discount_percent',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
