# Generated by Django 5.2.17 on 2026-09-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_annual_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='fr', max_length=5),
        ),
    ]
