# Generated by Django 5.2.17 on 2026-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_user_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='billing_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='billing_country',
            field=models.CharField(blank=True, default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
